/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nick
 */
public class battleship_playGame_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form battleship_playGame_JFrame
     */
    public battleship_playGame_JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        playerGridGamePage = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        oppGridGamePage = new javax.swing.JTable();
        rowILabelPlacementPage = new javax.swing.JLabel();
        rowGLabelPlacementPage = new javax.swing.JLabel();
        rowHLabelPlacementPage = new javax.swing.JLabel();
        rowELabelPlacementPage = new javax.swing.JLabel();
        rowFLabelPlacementPage = new javax.swing.JLabel();
        rowCLabelPlacementPage = new javax.swing.JLabel();
        rowDLabelPlacementPage = new javax.swing.JLabel();
        rowALabelPlacementPage = new javax.swing.JLabel();
        rowBLabelPlacementPage = new javax.swing.JLabel();
        rowJLabelPlacementPage = new javax.swing.JLabel();
        rowILabelPlacementPage1 = new javax.swing.JLabel();
        rowGLabelPlacementPage1 = new javax.swing.JLabel();
        rowHLabelPlacementPage1 = new javax.swing.JLabel();
        rowELabelPlacementPage1 = new javax.swing.JLabel();
        rowFLabelPlacementPage1 = new javax.swing.JLabel();
        rowCLabelPlacementPage1 = new javax.swing.JLabel();
        rowDLabelPlacementPage1 = new javax.swing.JLabel();
        rowALabelPlacementPage1 = new javax.swing.JLabel();
        rowBLabelPlacementPage1 = new javax.swing.JLabel();
        rowJLabelPlacementPage1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerGridGamePage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        playerGridGamePage.setMinimumSize(new java.awt.Dimension(150, 180));
        playerGridGamePage.setSelectionBackground(new java.awt.Color(255, 255, 255));
        playerGridGamePage.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(playerGridGamePage);

        oppGridGamePage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        oppGridGamePage.setMinimumSize(new java.awt.Dimension(150, 180));
        oppGridGamePage.setSelectionBackground(new java.awt.Color(255, 255, 255));
        oppGridGamePage.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(oppGridGamePage);

        rowILabelPlacementPage.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowILabelPlacementPage.setText("I");

        rowGLabelPlacementPage.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowGLabelPlacementPage.setText("G");

        rowHLabelPlacementPage.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowHLabelPlacementPage.setText("H");

        rowELabelPlacementPage.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowELabelPlacementPage.setText("E");

        rowFLabelPlacementPage.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowFLabelPlacementPage.setText("F");

        rowCLabelPlacementPage.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowCLabelPlacementPage.setText("C");

        rowDLabelPlacementPage.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowDLabelPlacementPage.setText("D");

        rowALabelPlacementPage.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowALabelPlacementPage.setText("A");
        rowALabelPlacementPage.setToolTipText("");

        rowBLabelPlacementPage.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowBLabelPlacementPage.setText("B");

        rowJLabelPlacementPage.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowJLabelPlacementPage.setText("J");

        rowILabelPlacementPage1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowILabelPlacementPage1.setText("I");

        rowGLabelPlacementPage1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowGLabelPlacementPage1.setText("G");

        rowHLabelPlacementPage1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowHLabelPlacementPage1.setText("H");

        rowELabelPlacementPage1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowELabelPlacementPage1.setText("E");

        rowFLabelPlacementPage1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowFLabelPlacementPage1.setText("F");

        rowCLabelPlacementPage1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowCLabelPlacementPage1.setText("C");

        rowDLabelPlacementPage1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowDLabelPlacementPage1.setText("D");

        rowALabelPlacementPage1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowALabelPlacementPage1.setText("A");
        rowALabelPlacementPage1.setToolTipText("");

        rowBLabelPlacementPage1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowBLabelPlacementPage1.setText("B");

        rowJLabelPlacementPage1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        rowJLabelPlacementPage1.setText("J");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rowBLabelPlacementPage, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowALabelPlacementPage, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowCLabelPlacementPage, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowDLabelPlacementPage, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowELabelPlacementPage, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowFLabelPlacementPage, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowGLabelPlacementPage, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowHLabelPlacementPage, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowILabelPlacementPage, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowJLabelPlacementPage, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rowBLabelPlacementPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowALabelPlacementPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowCLabelPlacementPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowDLabelPlacementPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowELabelPlacementPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowFLabelPlacementPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowGLabelPlacementPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowHLabelPlacementPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowILabelPlacementPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rowJLabelPlacementPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(rowALabelPlacementPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowBLabelPlacementPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowCLabelPlacementPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowDLabelPlacementPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowELabelPlacementPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowFLabelPlacementPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowGLabelPlacementPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowHLabelPlacementPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowILabelPlacementPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowJLabelPlacementPage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(rowALabelPlacementPage1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowBLabelPlacementPage1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowCLabelPlacementPage1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowDLabelPlacementPage1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowELabelPlacementPage1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowFLabelPlacementPage1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowGLabelPlacementPage1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowHLabelPlacementPage1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowILabelPlacementPage1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowJLabelPlacementPage1)))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(battleship_playGame_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(battleship_playGame_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(battleship_playGame_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(battleship_playGame_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new battleship_playGame_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable oppGridGamePage;
    private javax.swing.JTable playerGridGamePage;
    private javax.swing.JLabel rowALabelPlacementPage;
    private javax.swing.JLabel rowALabelPlacementPage1;
    private javax.swing.JLabel rowBLabelPlacementPage;
    private javax.swing.JLabel rowBLabelPlacementPage1;
    private javax.swing.JLabel rowCLabelPlacementPage;
    private javax.swing.JLabel rowCLabelPlacementPage1;
    private javax.swing.JLabel rowDLabelPlacementPage;
    private javax.swing.JLabel rowDLabelPlacementPage1;
    private javax.swing.JLabel rowELabelPlacementPage;
    private javax.swing.JLabel rowELabelPlacementPage1;
    private javax.swing.JLabel rowFLabelPlacementPage;
    private javax.swing.JLabel rowFLabelPlacementPage1;
    private javax.swing.JLabel rowGLabelPlacementPage;
    private javax.swing.JLabel rowGLabelPlacementPage1;
    private javax.swing.JLabel rowHLabelPlacementPage;
    private javax.swing.JLabel rowHLabelPlacementPage1;
    private javax.swing.JLabel rowILabelPlacementPage;
    private javax.swing.JLabel rowILabelPlacementPage1;
    private javax.swing.JLabel rowJLabelPlacementPage;
    private javax.swing.JLabel rowJLabelPlacementPage1;
    // End of variables declaration//GEN-END:variables
}
